# Generated by Django 3.0.5 on 2020-06-26 21:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Enviado por:')),
                ('motive', models.CharField(default='sugerencia', max_length=30, verbose_name=(('sugerencia', 'Sugerencia'), ('reclamo', 'Reclamo'), ('otros', 'Otros..')))),
                ('content', ckeditor.fields.RichTextField(verbose_name='contenido')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha de envio')),
            ],
        ),
    ]
