# Generated by Django 3.0.5 on 2020-06-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='motive',
            field=models.CharField(choices=[('sugerencia', 'Sugerencia'), ('reclamo', 'Reclamo'), ('otros', 'Otros..')], default='sugerencia', max_length=30),
        ),
    ]
